model:
  input_shape: [512, 512, 3]
  model_type: "EfficientNetB3"
  optimizer: "adam"
  loss_function: "binary_crossentropy"
  metrics: ["accuracy"]
  image_size: [512, 512, 3]
  include_top: False    
  weights: "imagenet"   
  classes: 1                

training:
  epochs: 1
  batch_size: 32
  auto_parallel_calls: True
  shuffle_data: True

evaluation:
  log_best_accuracy: True

